"""empty message

Revision ID: 086ad3613b10
Revises: 
Create Date: 2023-06-14 10:33:38.984099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086ad3613b10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.Date(), nullable=True),
    sa.Column('first_name', sa.String(length=25), nullable=False),
    sa.Column('last_name', sa.String(length=25), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('primary_muscle', sa.String(length=50), nullable=False),
    sa.Column('secondary_muscle', sa.String(length=50), nullable=True),
    sa.Column('tertiary_muscle', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=25), nullable=False),
    sa.Column('start_photo', sa.String(length=1000), nullable=True),
    sa.Column('end_photo', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises')
    op.drop_table('users')
    # ### end Alembic commands ###